import { useNavigate, useParams } from 'react-router';
import { trpc } from '@/providers/trpc';
import DeckPlayer from '@/components/player/DeckPlayer';
import SketchButton from '@/components/sketch/SketchButton';
import { ChevronLeft } from 'lucide-react';

/**
 * Replay the signed-in user's OWN saved customization of a lesson — the deck
 * they generated by spending a ticket. Free to replay (no new generation, no
 * ticket); to replace it they generate a new one from the repo.
 */
export default function MyCustomizationPlay() {
  const { slug = '', seq = '' } = useParams();
  const navigate = useNavigate();
  const lessonSeq = Number(seq);
  const query = trpc.repos.myCustomization.useQuery(
    { repoSlug: slug, lessonSeq },
    { enabled: !!slug && Number.isFinite(lessonSeq), retry: false },
  );

  const back = () => navigate(`/repos/${slug}`);

  if (query.isLoading) {
    return <div className="mx-auto max-w-[720px] px-4 py-16 text-center text-ink-faint">Opening your version…</div>;
  }
  if (query.isError || !query.data) {
    return (
      <div className="mx-auto max-w-[720px] px-4 py-16 text-center">
        <p className="font-display text-3xl text-ink">No saved customization</p>
        <p className="mt-2 text-ink-soft">
          You haven't generated a custom version of this lesson yet.
        </p>
        <SketchButton variant="secondary" className="mt-4" onClick={back}>
          <ChevronLeft className="h-4 w-4" /> Back
        </SketchButton>
      </div>
    );
  }

  const { deck, seed, toolSlug } = query.data;

  return (
    <DeckPlayer
      deck={deck}
      toolSlug={toolSlug}
      seed={seed}
      previouslyTaught={null}
      voiceURI={null}
      nextLessonTitle={null}
      commercial={null}
      walkthrough={null}
      onExit={back}
    />
  );
}
